accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (UserLoginForm)

app_name = 'accounts'


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/registration/login.html', redirect_authenticated_user=True,
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='accounts/registration/logout.html'), name='logout'),

    # registration
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/',
         views.account_activate, name='activate'),
    # user dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(
        template_name="accounts/user/delete_confirm.html"), name='delete_confirmation'),
    
]

task/urls.py
from django.urls import path

from . import views

app_name = 'task'


urlpatterns = [
    path('', views.home_view, name='home'),
    path('mytasks/', views.tasks, name='my_tasks'),
    path('task_detail/<str:pk>/', views.task_detail, name='task_detail'),
    path('task_update/<str:pk>/', views.task_update, name='task_update'),
    # path('task_status/<int:pk>/', views.task_status, name='task_status'),
    path('task_delete/<int:pk>/', views.task_delete, name='task_delete'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'task.views.custom_page_not_found_view'
handler500 = 'task.views.custom_error_view'
handler403 = 'task.views.custom_permission_denied_view'
handler400 = 'task.views.custom_bad_request_view'

task/models.py
from django.db import models

from accounts.models import CustomUser

class Task(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    dueDate = models.DateField()
    file = models.ImageField(upload_to='taskfiles/%Y/%m/%d/', blank=True)

    def __str__(self):
        return self.title

task/forms.py
from django import forms
from .models import Task


class DateInput(forms.DateInput):
    input_type = 'date'

class AddTaskForm(forms.ModelForm):

    title = forms.CharField(
        label='Title', help_text='Required')
    description = forms.Textarea()
    file = forms.ImageField(
        label='File', required=False)

 

    class Meta:
        model = Task
        fields = ( 'user' ,'title', 'description', 'dueDate', 'file')
        widgets = {
            'dueDate': DateInput(),
            'user': forms.TextInput(attrs={'value': '', 'id': 'id', 'type': 'hidden'}),
        }

    def __init__(self, *args, **kwargs):
        super(AddTaskForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['placeholder'] = self.fields['title'].label
        self.fields['description'].widget.attrs['placeholder'] = self.fields['description'].label
        self.fields['file'].widget.attrs.update({'class': 'fileupload'})

   

task/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .models import Task
from .forms import AddTaskForm

# Homepage
def home_view(request):
    return render(request, 'task/home.html')


# Add / View Tasks
@login_required
def tasks(request):
    task = Task.objects.filter( user = request.user )
    # pagination limit( 5)
    paginator = Paginator(task, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    # form post
    if request.method == 'POST':
        form = AddTaskForm(request.POST, request.FILES,)
        if form.is_valid():
            form.save()
            return redirect('task:my_tasks')

    else: 
        form = AddTaskForm()
        context = {
            'task': task,
            'form': form,
            'page_obj': page_obj,
        }
    return render(request, 'task/tasks.html', context)

# Task Detail


@login_required
def task_detail(request, pk):
    task = Task.objects.get(id=pk)
    context = {
        'task': task
    }
    return render(request, 'task/task_detail.html', context)

# Task Update


@login_required
def task_update(request, pk):
    task = Task.objects.get(id=pk)
    form = AddTaskForm(request.POST, request.FILES, instance = task)

    if form.is_valid():
        form.save()
        return redirect('task:task_detail', pk=task.id)
    else:
        form = AddTaskForm(instance = task)
    context = {
        'form': form,
        'task': task,
    }

    return render(request, 'task/task_update.html', context)



# Delete Task
@login_required
def task_delete(request, pk):
    try:
        task = Task.objects.get(id=pk, user=request.user)
        task.delete()
    except:
        pass
    return redirect('task:my_tasks')


# errors
def custom_page_not_found_view(request, exception):
    return render(request, "task/404.html", {})


def custom_error_view(request, exception=None):
    return render(request, "task/500.html", {})


def custom_permission_denied_view(request, exception=None):
    return render(request, "task/403.html", {})


def custom_bad_request_view(request, exception=None):
    return render(request, "task/400.html", {})

task/templates/task/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <script src="https://kit.fontawesome.com/c720c7699a.js" crossorigin="anonymous"></script>
    
    <title>{% block title %} {% endblock %}</title>
</head>
<body>

 

<nav class="navbar">
  <div class="nav-wrapper">
    
    <!--  -->
    <div class="nav-container" id="">
        <ul class="nav-items">
            <li class="nav-logo" id="">
                <a class="" href="/">TASKER</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="active nav-link" href="{% url 'task:my_tasks' %}">My Tasks</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:dashboard' %}">Dashboard</a>
            </li>
            
            <li style="float:right"  class="nav-item">
                <a class="nav-btn" href="{% url 'accounts:logout' %}">Logout</a> 
            </li>
            
            {% else %}
            <li style="float:right"  class="nav-item">
                <a class="nav-btn" href="{% url 'accounts:login' %}">Login</a> 
            </li>
            
            <li style="float:right"  class="nav-item">
                <a class="nav-btn" href="{% url 'accounts:register' %}">Register</a> 
            </li>
            {% endif %}
        </ul>

    </div>

    <!--  -->
  </div>
</nav>

    {% block content %}

    {% endblock %}


<div class="footer-container">
    <div class="footer-wrapper-container">
        <div class="footer-card">
            <p>TASKER</p>
        </div>
        {% if user.is_authenticated %}
        <div class="footer-card">
            <p>Tasks</p>
            <a href="">Add Task</a>
            <a href="">Another Link</a>
            <a href="">Another Link</a>
            
        </div>
        <div class="footer-card">
            <p>Account</p>
            <a href="">Update Profile</a>
            <a href="">Change Password</a>
        </div>
        <!--  -->
        {% else %}
        <div class="footer-card">
            <p>Help Center</p>
            <a href="">Q&A</a>
            <a href="">Customer Service</a>
           
        </div>
        <div class="footer-card">
            <p>Registration</p>
            <a href="{% url 'accounts:login' %}">Login</a>
            <a href="{% url 'accounts:register' %}">Register</a>
            <a href="">Forgot Password?</a>
            
        </div>
        
        {% endif %}
    </div>
    
</div>

<div class="footer-copyright">
    <p> 2021 Tasker USA, Inc. All rights reserve.</p>
</div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    
</body>
</html>

task/templates/task/home.html
{% extends 'task/base.html' %}
{% load static %}
<title>{% block title %} Tasker: Homepage (Make you life easier){% endblock %}</title>
{% block content %}



{% if user.is_authenticated %}
    <a class="nav-btn" href="{% url 'task:my_tasks' %}">Add a Task</a> 
    <div class="homepage-container">
    <div class="homepage-container-wrapper">
        <div class="homepage-heading">
            <h1>Welcome back, <p>{{ user.user_name }}</p></h1>
            <div class="call-to-action-btn">
                <a class="nav-btn" href="{% url 'accounts:login' %}">Add Task</a> 
                
            </div>
        </div>
        <div class="homepage-main-img">
            <img src="{% static 'img/Mobile note list-bro.png' %}" alt="">
        </div>
    </div>
</div>

{% else %}


<div class="homepage-container">
    <div class="homepage-container-wrapper">
        <div class="homepage-heading">
            <h1>Increase your productivity and organize your day with Tasker</h1>
            <div class="call-to-action-btn">
                <a class="nav-btn" href="{% url 'accounts:login' %}">Login</a> 
                <a class="nav-btn" href="{% url 'accounts:register' %}">Start Today</a> 
            </div>
        </div>
        <div class="homepage-main-img">
            <img src="{% static 'img/Mobile note list-bro.png' %}" alt="">
        </div>
    </div>
</div>

{% endif %}


<div class="section-one-container">
    <div class="section-one-wrapper-container">
        <div class="card">
            <h3>Simple, Powerful, Useful</h3>
        </div>
        <div class="card">
            <p>Organize your daily, weekly, ongoing tasks with just one click</p>
        </div>
        <div class="card"> 
            <div class="card-detail">
                <p>9.200k</p>
                <span>User used</span>
            </div> 
            <div class="card-detail">
                <p>100k</p>
                <span>Teams</span>
            </div>
            <div class="card-detail">
                <p>100+</p>
                <span>Templates</span>
            </div>
        </div>
    </div>
</div>


{% endblock %}

task/templates/task/task_detail.html
{% extends 'task/base.html' %}

<title>{% block title %} {{ task.title }} {% endblock %}</title>

{% block content %}



{% if user.id == task.user.id %}
<div class="task-detail-container">
    <div class="task-wrapper-container">
        <div class="go-back">
            <a href="{% url 'task:my_tasks' %}">Go back</a>
        </div>
        <div class="tasks-detail-title">
            <h1>{{ task.title }}</h1> 
        </div>
        <div class="task-detail-description">
            <p>{{ task.description }}</p>
        </div>
        <div class="task-detail-date">
            <p class="task-date-text">Due Date</p>
            <p class="task-date-datail">{{ task.dueDate }}</p>
        </div>
        {% if task.file %}
        <div class="task-detail-file">
            <p class="task-file-text">File</p>
            <a class="task-file-img" href="{{ task.file.url }}">View File</a>
        </div>
        {% else %}
        <div class="task-detail-file">
            <p class="task-file-text">File</p>
            <p class="task-no-file">You haven't uploaded one.</p>
        </div>
        {% endif %}
        <div class="task-detail-btn" >
            <a href="{% url 'task:task_update' task.pk %}">Update</a>
        </div>
    </div>
</div>
{% else %}

<p>you are not allowed here</p>

{% endif %}

{% endblock %}

task/templates/task/task_update.html
{% extends 'task/base.html' %}

<title>{% block title %} {{ task.title }} {% endblock %}</title>

{% block content %}


{% if user.id == task.user.id %}
<form action="" method="Post" enctype="multipart/form-data">
    {% csrf_token %}

<div class="task-update-container">
    <div class="task-update-wrapper-container">
        <div class="go-back">
            <a href="{% url 'task:task_detail' task.pk %}">Go back</a>
        </div>
        <div class="title-container">
                    <label class="title-label">
                    {{ form.user }}
                    
            </div>

            <script>
                var user = "{{ user.id }}";
                document.getElementById('id').value = user;
            </script>

        <div class="tasks-update-title">
            <h1>{{ form.title }}</h1> 
        </div>
        <div class="task-update-description">
            <p>{{ form.description }}</p>
        </div>
        <div class="task-update-date">
            <p class="task-update-date-text">Due Date</p>
            <p class="task-update-date-datail">{{ form.dueDate }}</p>
        </div>
        <div class="task-update-file">
            <p class="task-update-file-text">{{ form.file }}</p>
        </div> 
        <button class="task-update-btn" type="submit">Update</button>
    </div>
</div>

    
</form>

{% else %}

<p>you are not allowed here</p>

{% endif %}




{% endblock %}

task/templates/task/tasks.html
{% extends 'task/base.html' %}

{% block content %}



<div class="task-container">
    <div class="task-container-wrapper">
        <form action="" method="Post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="">
                {% if form.errors %}
                <p>Please correct the following errors:</p>
                {% for field in form %}
                {% if field.errors %}
                <div class="alert alert-primary" role="alert">
                    {{ field.label }}: {{ field.errors|striptags }}
                </div>
                {% endif %}
                {% endfor %}
                {% endif %}      
            </div>
            <!--  -->

            <div class="title-container">
                    <label class="title-label">
                    {{ form.user }}
                    
            </div>

            <script>
                var user = "{{ user.id }}";
                document.getElementById('id').value = user;
            </script>

  
                <div class="title-container">
                    <label class="title-label">
                    {{ form.title }}
                    <button class="title-btn fas fa-plus" type="submit"></button>
                </div>
           

            <!--  -->

            <div class="other-info-container">
                <!--  -->

                <div class="description-container">
                    {{ form.description }}
                </div>

                <!--  -->
                <div class="date-file-container">
                    <div class="label-container">   
                         {{ form.dueDate }}  
                    </div>

                    <div class="file-label-container">
                      {{ form.file }}
                    </div>
                   
                </div>

                <!--  -->
            </div>
        </form>
    </div>
</div>





<div class="tasks-container">
    <div class="tasks-wrapper-container">
        <!--  -->
        
        <div class="task-content">
            <h3>My Daily Tasks</h3>
            {% for task in page_obj %}

    
            <div class="single-task-container">

                <div class="taks-status">
                    <i class="far fa-circle"></i>
                   
                </div>
                <!--  -->
                <div class="task-title">
                    <p>{{ task.title|truncatechars:50 }}</p>
                </div>
                
                <div class="task-btns">
                    <a href="{% url 'task:task_detail'  task.pk %}"><i class="fas fa-info"></i></a>
                    <a href="{% url 'task:task_update'  task.pk %}"><i class="fas fa-pen"></i></a>
                    <a href="{% url 'task:task_delete'  task.pk %}"><i class="fas fa-trash"></i></a>
                </div>
                
                
            </div>
            {% endfor %}
        </div>

        
        <!--  -->
        
        <div class="profile-stats-container">
            <h3>What’s up, {{ user.user_name }} !</h3>
            <div class="profile-container">
                <p>My Profile</p>
                <a href="{% url 'accounts:dashboard' %}">Visit <i class="fas fa-caret-right"></i></a>
            </div>
            <div class="stats-container">
                <p>Total Tasks</p>
                <p class="total-tasks">{{ task.count }}</p>
            </div>
            <div class="stats-container">
                <p>Accomplishments</p>
                <p class="total-accomplishments">0</p>
            </div>
        </div>
        <!--  -->
    </div>
</div>


<div class="pagination">
    <div class="step-links">
        {% if page_obj.has_previous %}
            <a class="btn-first" href="?page=1">First</a>
            <a class="btn-previous" href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-arrow-circle-left"></i></a>
        {% endif %}

        
        <div class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </div>

        {% if page_obj.has_next %}
            <a class="btn-next" href="?page={{ page_obj.next_page_number }}"><i class="fa fa-arrow-circle-right"></i></a>
            <a class="btn-last" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    </div>
</div>


{% endblock %}